---
sidebar: sidebar 
permalink: task_vcp_upgrades.html 
summary: Actualice al último plugin de NetApp Element para VMware vCenter Server. 
keywords: netapp, vcp, vcenter, plugin, element, upgrade 
---
= Actualice el plugin
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Si desea actualizar el plugin de NetApp Element para vCenter Server, siga los pasos que se describen para la instalación. El complemento de vCenter para NetApp Element 5.1 está disponible fuera de las versiones de Element y NetApp HCI como parte de un paquete de servicios de gestión.

[NOTE]
====
* A partir del plugin de Element para vCenter 5.0, solo se admiten VMware vSphere 8.0 y 7.0.
* Cuando se actualiza del plugin de Element para vCenter 4.x a 5.x, los clústeres ya configurados con el plugin se pierden porque no se pueden copiar los datos de una instancia de vCenter en un plugin remoto. Debe volver a añadir los clústeres al plugin remoto. Esta es una actividad que solo debe hacer una vez al actualizar desde un plugin local a un plugin remoto.


====
.Pasos
Para actualizar el plugin, siga las instrucciones de la documentación de actualización de su producto:

* https://docs.netapp.com/us-en/hci/docs/task_vcp_upgrade_plugin.html["Actualice su sistema NetApp HCI"^]
* https://docs.netapp.com/us-en/element-software/upgrade/task_vcp_upgrade_plugin.html["Actualice su sistema de almacenamiento all-flash SolidFire"^]




== Obtenga más información

* https://library.netapp.com/ecm/ecm_download_file/ECMLP2885734["Notas de la versión del plugin de vCenter 5.1"^]
* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Management_services_for_Element_Software_and_NetApp_HCI/Management_Services_Release_Notes["Notas de la versión de los servicios de gestión y control de cloud híbrido"^]
* https://docs.netapp.com/us-en/hci/index.html["Documentación de NetApp HCI"^]
* http://mysupport.netapp.com/hci/resources["Recursos de NetApp HCI"^]
* https://www.netapp.com/data-storage/solidfire/documentation["Página SolidFire y Element Resources"^]

